# Generated by Django 3.2.1 on 2021-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentosIP',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('cont', models.IntegerField(default=0)),
                ('last_Peticion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nick', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=1000)),
                ('correo', models.CharField(max_length=70)),
                ('chatID', models.CharField(max_length=9)),
                ('tokenT', models.CharField(max_length=46)),
                ('llave_privada', models.TextField(max_length=400)),
                ('llave_publica', models.TextField(max_length=300)),
                ('iv', models.CharField(max_length=24)),
                ('salt', models.CharField(max_length=100)),
                ('tokenEnviado', models.CharField(max_length=8)),
            ],
        ),
    ]
