# Generated by Django 3.2.1 on 2021-06-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tokenTem',
            field=models.DateTimeField(null=True),
        ),
    ]
