# Generated by Django 3.2.1 on 2021-05-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tokenEnviado',
            field=models.CharField(default='', editable=False, max_length=8),
        ),
    ]
