# Generated by Django 3.2.1 on 2021-06-18 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='token_tem',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
