# Generated by Django 3.2.1 on 2021-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1', '0002_usuarios_tokenenviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tokenEnviado',
            field=models.CharField(max_length=8),
        ),
    ]
